#!/bin/sh
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
cargo run --example client &
