name: Clippy

on:
  push:
    branches: '*'
  pull_request:
    branches: 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used  -W clippy::missing_docs_in_private_items -W clippy::too_many_lines -W clippy::inefficient_to_string -D warnings